name: build

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Create properties
        env:
          DEV_PROPERTIES: ${{ secrets.DEV_PROPERTIES }}
        run: |
          echo $DEV_PROPERTIES > dev.properties
          cat dev.properties
      - name: Assemble foss flavor
        run: ./gradlew assembleFossDebug
      - name: Assemble Google Play flavor
        run: ./gradlew assemblePlayDebug
