name: dependencies
on:
  push:
    branches:
      - dev
jobs:
  acquire-dependencies:
    name: Dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Submit dependencies
        uses: mikepenz/gradle-dependency-submission@v0.9.1
        with:
          use-gradlew: true
          gradle-build-module: |-
            :app
